# Generated by Django 4.0.6 on 2022-07-07 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_topic_alter_post_timeupdated_comment_post_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timeCreated',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
